enum ActionLogType {
	DATABASE = 'DATABASE',
	API = 'API',
	FIREBASE_NOTIFICATION = 'FIREBASE_NOTIFICATION',
	MOBILE_NOTIFICATION = 'MOBILE_NOTIFICATION',
	EMAIL = 'EMAIL'
}

module.exports = ActionLogType;
